"""create initial tables

Revision ID: 4db7af2542d3
Revises: 
Create Date: 2026-09-21 07:01:22.117455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db7af2542d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_name')
    )
    op.create_index(op.f('ix_register_client_id'), 'register', ['client_id'], unique=True)
    op.create_index(op.f('ix_register_is_active'), 'register', ['is_active'], unique=False)
    op.create_table('user_queries',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('external_prompt_id', sa.String(length=255), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_user_queries_app_id'), 'user_queries', ['app_id'], unique=False)
    op.create_index(op.f('ix_user_queries_conversation_id'), 'user_queries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_user_queries_external_prompt_id'), 'user_queries', ['external_prompt_id'], unique=False)
    op.create_index(op.f('ix_user_queries_is_active'), 'user_queries', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_queries_is_active'), table_name='user_queries')
    op.drop_index(op.f('ix_user_queries_external_prompt_id'), table_name='user_queries')
    op.drop_index(op.f('ix_user_queries_conversation_id'), table_name='user_queries')
    op.drop_index(op.f('ix_user_queries_app_id'), table_name='user_queries')
    op.drop_table('user_queries')
    op.drop_index(op.f('ix_register_is_active'), table_name='register')
    op.drop_index(op.f('ix_register_client_id'), table_name='register')
    op.drop_table('register')
    # ### end Alembic commands ###
