"""fallback models

Revision ID: 86a3dbae08e1
Revises: 4db7af2542d3
Create Date: 2026-09-23 08:20:44.623975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a3dbae08e1'
down_revision: Union[str, Sequence[str], None] = '4db7af2542d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_fallback_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('llm_model', sa.String(length=255), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=1000), nullable=False),
    sa.Column('daily_token_limit', sa.BigInteger(), nullable=False),
    sa.Column('used_tokens', sa.BigInteger(), nullable=False),
    sa.Column('daily_request_limit', sa.Integer(), nullable=False),
    sa.Column('used_requests', sa.Integer(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=False),
    sa.Column('tpm_limit', sa.BigInteger(), nullable=False),
    sa.Column('minute_requests', sa.Integer(), nullable=False),
    sa.Column('minute_tokens', sa.BigInteger(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_rate_limited', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_fallback_models_is_active'), 'llm_fallback_models', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_fallback_models_is_active'), table_name='llm_fallback_models')
    op.drop_table('llm_fallback_models')
    # ### end Alembic commands ###
